name: Build and Publish GAP

on:
  push:
    tags:
      - '*'

jobs:
    build-firefox:
        name: Build and Publish Extension for Firefox
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3
        
          - name: Hack to remove incognito split for Firefox
            run: |
                 cd src
                 sed -i '/"incognito": "split",/d' ./manifest.json

          - name: "web-ext build"
            id: web-ext-build
            uses: kewisch/action-web-ext@v1
            with:
                cmd: build
                source: src

          - name: "web-ext sign"
            id: web-ext-sign
            uses: kewisch/action-web-ext@v1
            with:
                cmd: sign
                source: ${{ steps.web-ext-build.outputs.target }}
                channel: unlisted
                apiKey: ${{ secrets.FIREFOX_JWT_ISSUER }}
                apiSecret: ${{ secrets.FIREFOX_JWT_SECRET }}
                timeout: 900000

          - name: Upload archive
            uses: actions/upload-artifact@v3
            with:
                name: GAP-${{steps.web-ext-sign.outputs}}
                path: build/Build/Products/Release/Z-universal.app.zip

          - name: "Create Release"
            uses: softprops/action-gh-release@v1
            with:
                files: ${{ steps.web-ext-sign.outputs.target }}
